/* 
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DocsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DocsApiTests
    {
        private DocsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DocsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DocsApi
            //Assert.IsInstanceOfType(typeof(DocsApi), instance, "instance is a DocsApi");
        }

        
        /// <summary>
        /// Test GRPCCsharpCodeGen
        /// </summary>
        [Test]
        public void GRPCCsharpCodeGenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GRPCCsharpCodeGen();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test GRPCProtoFile
        /// </summary>
        [Test]
        public void GRPCProtoFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GRPCProtoFile();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SwaggerCsharpCodeGen
        /// </summary>
        [Test]
        public void SwaggerCsharpCodeGenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.SwaggerCsharpCodeGen();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
