/* 
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MazeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MazeApiTests
    {
        private MazeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MazeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MazeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MazeApi
            //Assert.IsInstanceOfType(typeof(MazeApi), instance, "instance is a MazeApi");
        }

        
        /// <summary>
        /// Test CollectScore
        /// </summary>
        [Test]
        public void CollectScoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CollectScore();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test Enter
        /// </summary>
        [Test]
        public void EnterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string mazeName = null;
            //var response = instance.Enter(mazeName);
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test ExitMaze
        /// </summary>
        [Test]
        public void ExitMazeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ExitMaze();
            
        }
        
        /// <summary>
        /// Test MoveDown
        /// </summary>
        [Test]
        public void MoveDownTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MoveDown();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test MoveLeft
        /// </summary>
        [Test]
        public void MoveLeftTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MoveLeft();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test MoveRight
        /// </summary>
        [Test]
        public void MoveRightTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MoveRight();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test MoveUp
        /// </summary>
        [Test]
        public void MoveUpTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MoveUp();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test PossibleActions
        /// </summary>
        [Test]
        public void PossibleActionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PossibleActions();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
    }

}
