/* 
 * A-maze-ing API
 *
 * This document describes the API of the A-maze-ing evening server.    This API consists of three different endpoints, which are detailed below.   - To register yourself as a player use the Player endpoint.   - To get information about the available mazes and enter a specific maze use the Mazes endpoint.   - To navigate a maze use the Maze endpoint.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MazeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class MazeApiTests
    {
        private MazeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new MazeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MazeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' MazeApi
            //Assert.IsInstanceOfType(typeof(MazeApi), instance, "instance is a MazeApi");
        }

        
        /// <summary>
        /// Test CollectScore
        /// </summary>
        [Test]
        public void CollectScoreTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CollectScore();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test ExitMaze
        /// </summary>
        [Test]
        public void ExitMazeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ExitMaze();
            
        }
        
        /// <summary>
        /// Test Move
        /// </summary>
        [Test]
        public void MoveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string direction = null;
            //var response = instance.Move(direction);
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
        /// <summary>
        /// Test PossibleActions
        /// </summary>
        [Test]
        public void PossibleActionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.PossibleActions();
            //Assert.IsInstanceOf<PossibleActionsAndCurrentScore> (response, "response is PossibleActionsAndCurrentScore");
        }
        
    }

}
