/* 
 * A-maze-ing API
 *
 * This document describes the API of the A-maze-ing evening server.    This API consists of three different endpoints, which are detailed below.   - To register yourself as a player use the Player endpoint.   - To get information about the available mazes and enter a specific maze use the Mazes endpoint.   - To navigate a maze use the Maze endpoint.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The data structure that represents information related to a player.
    /// </summary>
    [DataContract]
    public partial class PlayerInfo :  IEquatable<PlayerInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public PlayerInfo()
        {
        }
        
        /// <summary>
        /// The public unique identifier of a player.
        /// </summary>
        /// <value>The public unique identifier of a player.</value>
        [DataMember(Name="playerId", EmitDefaultValue=false)]
        public string PlayerId { get; private set; }

        /// <summary>
        /// The name a player has chosen to represent her.
        /// </summary>
        /// <value>The name a player has chosen to represent her.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; private set; }

        /// <summary>
        /// An indication of whether a player is currently playing a maze or not.
        /// </summary>
        /// <value>An indication of whether a player is currently playing a maze or not.</value>
        [DataMember(Name="isInMaze", EmitDefaultValue=false)]
        public bool? IsInMaze { get; private set; }

        /// <summary>
        /// The name of the maze the player is currently playing. Might be null if player  is not currently playing a maze.
        /// </summary>
        /// <value>The name of the maze the player is currently playing. Might be null if player  is not currently playing a maze.</value>
        [DataMember(Name="maze", EmitDefaultValue=false)]
        public string Maze { get; private set; }

        /// <summary>
        /// Wink wink.
        /// </summary>
        /// <value>Wink wink.</value>
        [DataMember(Name="hasFoundEasterEgg", EmitDefaultValue=false)]
        public bool? HasFoundEasterEgg { get; private set; }

        /// <summary>
        /// How much score the player has in her hand. Only available if player is playing a maze.
        /// </summary>
        /// <value>How much score the player has in her hand. Only available if player is playing a maze.</value>
        [DataMember(Name="mazeScoreInHand", EmitDefaultValue=false)]
        public int? MazeScoreInHand { get; private set; }

        /// <summary>
        /// How much score the player has in her bag. Only available if player is playing a maze.
        /// </summary>
        /// <value>How much score the player has in her bag. Only available if player is playing a maze.</value>
        [DataMember(Name="mazeScoreInBag", EmitDefaultValue=false)]
        public int? MazeScoreInBag { get; private set; }

        /// <summary>
        /// The accumulated score across all played mazes.
        /// </summary>
        /// <value>The accumulated score across all played mazes.</value>
        [DataMember(Name="playerScore", EmitDefaultValue=false)]
        public int? PlayerScore { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlayerInfo {\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsInMaze: ").Append(IsInMaze).Append("\n");
            sb.Append("  Maze: ").Append(Maze).Append("\n");
            sb.Append("  HasFoundEasterEgg: ").Append(HasFoundEasterEgg).Append("\n");
            sb.Append("  MazeScoreInHand: ").Append(MazeScoreInHand).Append("\n");
            sb.Append("  MazeScoreInBag: ").Append(MazeScoreInBag).Append("\n");
            sb.Append("  PlayerScore: ").Append(PlayerScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlayerInfo);
        }

        /// <summary>
        /// Returns true if PlayerInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of PlayerInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlayerInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PlayerId == input.PlayerId ||
                    (this.PlayerId != null &&
                    this.PlayerId.Equals(input.PlayerId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.IsInMaze == input.IsInMaze ||
                    (this.IsInMaze != null &&
                    this.IsInMaze.Equals(input.IsInMaze))
                ) && 
                (
                    this.Maze == input.Maze ||
                    (this.Maze != null &&
                    this.Maze.Equals(input.Maze))
                ) && 
                (
                    this.HasFoundEasterEgg == input.HasFoundEasterEgg ||
                    (this.HasFoundEasterEgg != null &&
                    this.HasFoundEasterEgg.Equals(input.HasFoundEasterEgg))
                ) && 
                (
                    this.MazeScoreInHand == input.MazeScoreInHand ||
                    (this.MazeScoreInHand != null &&
                    this.MazeScoreInHand.Equals(input.MazeScoreInHand))
                ) && 
                (
                    this.MazeScoreInBag == input.MazeScoreInBag ||
                    (this.MazeScoreInBag != null &&
                    this.MazeScoreInBag.Equals(input.MazeScoreInBag))
                ) && 
                (
                    this.PlayerScore == input.PlayerScore ||
                    (this.PlayerScore != null &&
                    this.PlayerScore.Equals(input.PlayerScore))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlayerId != null)
                    hashCode = hashCode * 59 + this.PlayerId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.IsInMaze != null)
                    hashCode = hashCode * 59 + this.IsInMaze.GetHashCode();
                if (this.Maze != null)
                    hashCode = hashCode * 59 + this.Maze.GetHashCode();
                if (this.HasFoundEasterEgg != null)
                    hashCode = hashCode * 59 + this.HasFoundEasterEgg.GetHashCode();
                if (this.MazeScoreInHand != null)
                    hashCode = hashCode * 59 + this.MazeScoreInHand.GetHashCode();
                if (this.MazeScoreInBag != null)
                    hashCode = hashCode * 59 + this.MazeScoreInBag.GetHashCode();
                if (this.PlayerScore != null)
                    hashCode = hashCode * 59 + this.PlayerScore.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
