/* 
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MazeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MazeInfoTests
    {
        // TODO uncomment below to declare an instance variable for MazeInfo
        //private MazeInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MazeInfo
            //instance = new MazeInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MazeInfo
        /// </summary>
        [Test]
        public void MazeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MazeInfo
            //Assert.IsInstanceOfType<MazeInfo> (instance, "variable 'instance' is a MazeInfo");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TotalTiles'
        /// </summary>
        [Test]
        public void TotalTilesTest()
        {
            // TODO unit test for the property 'TotalTiles'
        }
        /// <summary>
        /// Test the property 'PotentialReward'
        /// </summary>
        [Test]
        public void PotentialRewardTest()
        {
            // TODO unit test for the property 'PotentialReward'
        }

    }

}
