/* 
 * A-maze-ing API
 *
 * This document describes the API of the A-maze-ing evening server.    This API consists of three different endpoints, which are detailed below.   - To register yourself as a player use the Player endpoint.   - To get information about the available mazes and enter a specific maze use the Mazes endpoint.   - To navigate a maze use the Maze endpoint.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MoveAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MoveActionTests
    {
        // TODO uncomment below to declare an instance variable for MoveAction
        //private MoveAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MoveAction
            //instance = new MoveAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MoveAction
        /// </summary>
        [Test]
        public void MoveActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MoveAction
            //Assert.IsInstanceOfType<MoveAction> (instance, "variable 'instance' is a MoveAction");
        }


        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'IsStart'
        /// </summary>
        [Test]
        public void IsStartTest()
        {
            // TODO unit test for the property 'IsStart'
        }
        /// <summary>
        /// Test the property 'AllowsExit'
        /// </summary>
        [Test]
        public void AllowsExitTest()
        {
            // TODO unit test for the property 'AllowsExit'
        }
        /// <summary>
        /// Test the property 'AllowsScoreCollection'
        /// </summary>
        [Test]
        public void AllowsScoreCollectionTest()
        {
            // TODO unit test for the property 'AllowsScoreCollection'
        }
        /// <summary>
        /// Test the property 'HasBeenVisited'
        /// </summary>
        [Test]
        public void HasBeenVisitedTest()
        {
            // TODO unit test for the property 'HasBeenVisited'
        }
        /// <summary>
        /// Test the property 'RewardOnDestination'
        /// </summary>
        [Test]
        public void RewardOnDestinationTest()
        {
            // TODO unit test for the property 'RewardOnDestination'
        }

    }

}
