/* 
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PossibleActionsAndCurrentScore
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PossibleActionsAndCurrentScoreTests
    {
        // TODO uncomment below to declare an instance variable for PossibleActionsAndCurrentScore
        //private PossibleActionsAndCurrentScore instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PossibleActionsAndCurrentScore
            //instance = new PossibleActionsAndCurrentScore();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PossibleActionsAndCurrentScore
        /// </summary>
        [Test]
        public void PossibleActionsAndCurrentScoreInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PossibleActionsAndCurrentScore
            //Assert.IsInstanceOfType<PossibleActionsAndCurrentScore> (instance, "variable 'instance' is a PossibleActionsAndCurrentScore");
        }


        /// <summary>
        /// Test the property 'PossibleMoveActions'
        /// </summary>
        [Test]
        public void PossibleMoveActionsTest()
        {
            // TODO unit test for the property 'PossibleMoveActions'
        }
        /// <summary>
        /// Test the property 'CanCollectScoreHere'
        /// </summary>
        [Test]
        public void CanCollectScoreHereTest()
        {
            // TODO unit test for the property 'CanCollectScoreHere'
        }
        /// <summary>
        /// Test the property 'CanExitMazeHere'
        /// </summary>
        [Test]
        public void CanExitMazeHereTest()
        {
            // TODO unit test for the property 'CanExitMazeHere'
        }
        /// <summary>
        /// Test the property 'CurrentScoreInHand'
        /// </summary>
        [Test]
        public void CurrentScoreInHandTest()
        {
            // TODO unit test for the property 'CurrentScoreInHand'
        }
        /// <summary>
        /// Test the property 'CurrentScoreInBag'
        /// </summary>
        [Test]
        public void CurrentScoreInBagTest()
        {
            // TODO unit test for the property 'CurrentScoreInBag'
        }

    }

}
