/* 
 * A-maze-ing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDocsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string GRPCCsharpCodeGen ();

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GRPCCsharpCodeGenWithHttpInfo ();
        /// <summary>
        /// 📜 The gRPC proto file for the client code generation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string GRPCProtoFile ();

        /// <summary>
        /// 📜 The gRPC proto file for the client code generation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GRPCProtoFileWithHttpInfo ();
        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string SwaggerCsharpCodeGen ();

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SwaggerCsharpCodeGenWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GRPCCsharpCodeGenAsync ();

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GRPCCsharpCodeGenAsyncWithHttpInfo ();
        /// <summary>
        /// 📜 The gRPC proto file for the client code generation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GRPCProtoFileAsync ();

        /// <summary>
        /// 📜 The gRPC proto file for the client code generation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GRPCProtoFileAsyncWithHttpInfo ();
        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SwaggerCsharpCodeGenAsync ();

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec.
        /// </summary>
        /// <remarks>
        /// Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SwaggerCsharpCodeGenAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DocsApi : IDocsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DocsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DocsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DocsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string GRPCCsharpCodeGen ()
        {
             ApiResponse<string> localVarResponse = GRPCCsharpCodeGenWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > GRPCCsharpCodeGenWithHttpInfo ()
        {

            var localVarPath = "/docs/codeGen/gRPC/csharp";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/markdown; charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GRPCCsharpCodeGen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GRPCCsharpCodeGenAsync ()
        {
             ApiResponse<string> localVarResponse = await GRPCCsharpCodeGenAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from a gRPC proto file. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GRPCCsharpCodeGenAsyncWithHttpInfo ()
        {

            var localVarPath = "/docs/codeGen/gRPC/csharp";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/markdown; charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GRPCCsharpCodeGen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// 📜 The gRPC proto file for the client code generation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string GRPCProtoFile ()
        {
             ApiResponse<string> localVarResponse = GRPCProtoFileWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// 📜 The gRPC proto file for the client code generation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > GRPCProtoFileWithHttpInfo ()
        {

            var localVarPath = "/docs/codeGen/gRPC/proto";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/protobuf; charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GRPCProtoFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// 📜 The gRPC proto file for the client code generation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GRPCProtoFileAsync ()
        {
             ApiResponse<string> localVarResponse = await GRPCProtoFileAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// 📜 The gRPC proto file for the client code generation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GRPCProtoFileAsyncWithHttpInfo ()
        {

            var localVarPath = "/docs/codeGen/gRPC/proto";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/protobuf; charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GRPCProtoFile", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string SwaggerCsharpCodeGen ()
        {
             ApiResponse<string> localVarResponse = SwaggerCsharpCodeGenWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SwaggerCsharpCodeGenWithHttpInfo ()
        {

            var localVarPath = "/docs/codeGen/swagger/csharp";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/markdown; charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SwaggerCsharpCodeGen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SwaggerCsharpCodeGenAsync ()
        {
             ApiResponse<string> localVarResponse = await SwaggerCsharpCodeGenAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// 📜 Some pointers to having csharp client code generation from the Swagger/Open API spec. Use these guidelines to create a minimal application that allows you to communicate with our servers.     These guidelines provide automatically generated C# client code, with IntelliSense documentation, serialization and de-serialization and a way to authenticate your requests.    Keep in mind this is provided under the \&quot;Works on my machine, YMMV.\&quot;™ age-old agreement. 😀 Enjoy!
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SwaggerCsharpCodeGenAsyncWithHttpInfo ()
        {

            var localVarPath = "/docs/codeGen/swagger/csharp";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/markdown; charset=UTF-8"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization")));
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SwaggerCsharpCodeGen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
