/* 
 * A-maze-ing API
 *
 * This document describes the API of the A-maze-ing evening server.    This API consists of three different endpoints, which are detailed below.   - To register yourself as a player use the Player endpoint.   - To get information about the available mazes and enter a specific maze use the Mazes endpoint.   - To navigate a maze use the Maze endpoint.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMazesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 📜 All the mazes that exist in the game.
        /// </summary>
        /// <remarks>
        /// Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;MazeInfo&gt;</returns>
        List<MazeInfo> All ();

        /// <summary>
        /// 📜 All the mazes that exist in the game.
        /// </summary>
        /// <remarks>
        /// Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;MazeInfo&gt;</returns>
        ApiResponse<List<MazeInfo>> AllWithHttpInfo ();
        /// <summary>
        /// 🌟 Enter a maze.
        /// </summary>
        /// <remarks>
        /// Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>PossibleActionsAndCurrentScore</returns>
        PossibleActionsAndCurrentScore Enter (string mazeName);

        /// <summary>
        /// 🌟 Enter a maze.
        /// </summary>
        /// <remarks>
        /// Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>ApiResponse of PossibleActionsAndCurrentScore</returns>
        ApiResponse<PossibleActionsAndCurrentScore> EnterWithHttpInfo (string mazeName);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 📜 All the mazes that exist in the game.
        /// </summary>
        /// <remarks>
        /// Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;MazeInfo&gt;</returns>
        System.Threading.Tasks.Task<List<MazeInfo>> AllAsync ();

        /// <summary>
        /// 📜 All the mazes that exist in the game.
        /// </summary>
        /// <remarks>
        /// Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;MazeInfo&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<MazeInfo>>> AllAsyncWithHttpInfo ();
        /// <summary>
        /// 🌟 Enter a maze.
        /// </summary>
        /// <remarks>
        /// Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>Task of PossibleActionsAndCurrentScore</returns>
        System.Threading.Tasks.Task<PossibleActionsAndCurrentScore> EnterAsync (string mazeName);

        /// <summary>
        /// 🌟 Enter a maze.
        /// </summary>
        /// <remarks>
        /// Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>Task of ApiResponse (PossibleActionsAndCurrentScore)</returns>
        System.Threading.Tasks.Task<ApiResponse<PossibleActionsAndCurrentScore>> EnterAsyncWithHttpInfo (string mazeName);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MazesApi : IMazesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MazesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MazesApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MazesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MazesApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// 📜 All the mazes that exist in the game. Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;MazeInfo&gt;</returns>
        public List<MazeInfo> All ()
        {
             ApiResponse<List<MazeInfo>> localVarResponse = AllWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// 📜 All the mazes that exist in the game. Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;MazeInfo&gt;</returns>
        public ApiResponse< List<MazeInfo> > AllWithHttpInfo ()
        {

            var localVarPath = "/api/mazes/all";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("All", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<MazeInfo>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<MazeInfo>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<MazeInfo>)));
        }

        /// <summary>
        /// 📜 All the mazes that exist in the game. Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;MazeInfo&gt;</returns>
        public async System.Threading.Tasks.Task<List<MazeInfo>> AllAsync ()
        {
             ApiResponse<List<MazeInfo>> localVarResponse = await AllAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// 📜 All the mazes that exist in the game. Even though you can only play a maze once, this method will return all the mazes. This is not laziness from the server side, this is to make it slightly more \&quot;interesting\&quot;, because you need to keep track of the mazes you have already played on your implementation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;MazeInfo&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<MazeInfo>>> AllAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/mazes/all";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("All", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<MazeInfo>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<MazeInfo>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<MazeInfo>)));
        }

        /// <summary>
        /// 🌟 Enter a maze. Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>PossibleActionsAndCurrentScore</returns>
        public PossibleActionsAndCurrentScore Enter (string mazeName)
        {
             ApiResponse<PossibleActionsAndCurrentScore> localVarResponse = EnterWithHttpInfo(mazeName);
             return localVarResponse.Data;
        }

        /// <summary>
        /// 🌟 Enter a maze. Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>ApiResponse of PossibleActionsAndCurrentScore</returns>
        public ApiResponse< PossibleActionsAndCurrentScore > EnterWithHttpInfo (string mazeName)
        {
            // verify the required parameter 'mazeName' is set
            if (mazeName == null)
                throw new ApiException(400, "Missing required parameter 'mazeName' when calling MazesApi->Enter");

            var localVarPath = "/api/mazes/enter";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (mazeName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "mazeName", mazeName)); // query parameter

            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Enter", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PossibleActionsAndCurrentScore>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PossibleActionsAndCurrentScore) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PossibleActionsAndCurrentScore)));
        }

        /// <summary>
        /// 🌟 Enter a maze. Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>Task of PossibleActionsAndCurrentScore</returns>
        public async System.Threading.Tasks.Task<PossibleActionsAndCurrentScore> EnterAsync (string mazeName)
        {
             ApiResponse<PossibleActionsAndCurrentScore> localVarResponse = await EnterAsyncWithHttpInfo(mazeName);
             return localVarResponse.Data;

        }

        /// <summary>
        /// 🌟 Enter a maze. Keep in mind that you can only be playing one maze at a time. Invoking this method when you are already in a maze will result in a failure. Also, you can only play the same maze once. If you wish to play the same maze \&quot;multiple times\&quot;, you need to request to forget your player data (via the player API).
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mazeName">What maze do you wish to enter.</param>
        /// <returns>Task of ApiResponse (PossibleActionsAndCurrentScore)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PossibleActionsAndCurrentScore>> EnterAsyncWithHttpInfo (string mazeName)
        {
            // verify the required parameter 'mazeName' is set
            if (mazeName == null)
                throw new ApiException(400, "Missing required parameter 'mazeName' when calling MazesApi->Enter");

            var localVarPath = "/api/mazes/enter";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (mazeName != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "mazeName", mazeName)); // query parameter

            // authentication (User token) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Enter", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PossibleActionsAndCurrentScore>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PossibleActionsAndCurrentScore) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PossibleActionsAndCurrentScore)));
        }

    }
}
